# Generated by Django 2.0.dev20170825085001 on 2017-08-27 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('postal_code', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Type', models.CharField(choices=[('bi', 'Bike'), ('ls', 'ls'), ('sp', 'sp'), ('fn', 'fn'), ('bk', 'bk'), ('na', 'na')], default='na', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifiedTrade', models.BooleanField(default=False)),
                ('ownerAnswer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('description', models.TextField(null=True)),
                ('active_start_date', models.DateField(null=True)),
                ('been_traded', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('filename', models.CharField(max_length=140, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_savante.Category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='individualtrades',
            name='askerItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='askerItem', to='trade_savante.TradeItem'),
        ),
        migrations.AddField(
            model_name='individualtrades',
            name='ownerItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerItem', to='trade_savante.TradeItem'),
        ),
    ]
