# Generated by Django 2.0.dev20170825085001 on 2017-08-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_Type',
            new_name='category',
        ),
    ]
