# Generated by Django 2.0.dev20170825085001 on 2017-08-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0003_auto_20170827_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('bi', 'Bike'), ('ls', 'Leisure'), ('sp', 'Sports'), ('fn', 'Fashion'), ('bk', 'Books'), ('na', 'Not applicable')], default='na', max_length=2),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='category',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
