# Generated by Django 2.0.dev20170825085001 on 2017-08-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0004_auto_20170828_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='tradeitem',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='category',
            field=models.CharField(choices=[('bike', 'Bike'), ('leisure', 'Leisure'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('bike', 'Books'), ('na', 'Not applicable')], max_length=20),
        ),
    ]
