# Generated by Django 2.0.dev20170825085001 on 2017-08-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0005_auto_20170828_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeitem',
            name='file_name',
        ),
        migrations.AddField(
            model_name='tradeitem',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
