# Generated by Django 2.0.dev20170825085001 on 2017-08-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0007_auto_20170828_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='image',
            field=models.ImageField(null=True, upload_to='tradesavante'),
        ),
    ]
