# Generated by Django 2.0.dev20170825085001 on 2017-08-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0008_auto_20170829_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='active_start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
