# Generated by Django 2.0.dev20170825085001 on 2017-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0009_auto_20170829_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtrades',
            name='ownerAnswer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tradesavante'),
        ),
    ]
