# Generated by Django 2.0.dev20170825085001 on 2017-09-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0010_auto_20170905_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkNumber', models.IntegerField(default=0)),
                ('isClosed', models.BooleanField(default=False)),
                ('tradeConnection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_savante.IndividualTrades')),
            ],
        ),
    ]
