# Generated by Django 2.0.dev20170825085001 on 2017-09-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0012_tradesequence_sequencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesequence',
            name='name',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tradesequence',
            name='tradeConnection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_savante.TradeItem'),
        ),
    ]
