# Generated by Django 2.0.dev20170825085001 on 2017-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0013_auto_20170908_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesequence',
            name='sequenceid',
            field=models.IntegerField(default=1),
        ),
    ]
