# Generated by Django 2.0.dev20170825085001 on 2017-09-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0015_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordsearch', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tradeitem',
            name='key_words',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='searchkeywords',
            name='itemsearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_savante.TradeItem'),
        ),
    ]
