# Generated by Django 2.0.dev20170825085001 on 2017-09-16 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0016_auto_20170916_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeitem',
            name='key_words',
        ),
    ]
