# Generated by Django 2.0.dev20170825085001 on 2017-09-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0018_auto_20170917_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='category',
            field=models.CharField(choices=[('housing', 'Housing'), ('electronics', 'Electronics'), ('automotive', 'Automotive'), ('bike', 'Bike'), ('leisure', 'Leisure'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('bike', 'Books'), ('money', 'Money'), ('services', 'Services'), ('na', 'Not applicable')], max_length=20),
        ),
    ]
