# Generated by Django 2.0.dev20170825085001 on 2017-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0019_auto_20170918_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='asking_for',
            field=models.TextField(null=True),
        ),
    ]
