# Generated by Django 2.0.dev20170825085001 on 2017-09-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0020_tradeitem_asking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='category',
            field=models.CharField(choices=[('na', 'Not applicable'), ('housing', 'Housing'), ('electronics', 'Electronics'), ('automotive', 'Automotive'), ('bike', 'Bike'), ('leisure', 'Leisure'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('bike', 'Books'), ('money', 'Money'), ('services', 'Services')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tradesequence',
            name='tradeConnection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_savante.IndividualTrades'),
        ),
    ]
