# Generated by Django 2.0.dev20170825085001 on 2017-09-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_savante', '0021_auto_20170919_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesequence',
            name='name',
        ),
    ]
